package nz.ac.canterbury.seng302.gardenersgrove.component;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import nz.ac.canterbury.seng302.gardenersgrove.exceptions.AccountDisabledException;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.web.authentication.AuthenticationFailureHandler;

import java.io.IOException;

/**
 * Handles different brands of login failure generated by the SecurityConfig formLogin matcher.
 */
@Configuration
public class CustomAuthenticationFailureHandler implements AuthenticationFailureHandler {
    @Override
    public void onAuthenticationFailure(HttpServletRequest request, HttpServletResponse response,
                                        AuthenticationException exception) throws IOException {
        // Catches the specific type of error and adds attributes based on it
        if (exception instanceof BadCredentialsException) {
            request.getSession().setAttribute("error", "badCredentials");
        } else if (exception instanceof AccountDisabledException) {
            request.getSession().setAttribute("error", "accountDisabled");
            request.getSession().setAttribute("accountDisabledDate", exception.getMessage());
        }
        response.sendRedirect("./login?error");
    }
}
